### ISSUE TITLE
Expand folder, large spacing

### ISSUE THREAD

**Issue by lepig** [andresmichel/one-dark-theme#1]
It's not a bug, but I don't feel good. i like boxy theme folder style. 

this is boxy theme
![1](https://cloud.githubusercontent.com/assets/5689279/21674723/ed6c25ec-d369-11e6-8367-00524a4c1870.jpeg)

this is one-dark-theme
![2](https://cloud.githubusercontent.com/assets/5689279/21674724/ed6e108c-d369-11e6-8cc9-05f8c95372e7.jpg)

**Comment by andresmichel** [comment]
This theme is not finished yet but the main idea is to make Sublime Text look as close as possible to Atom One Dark theme.

![screenshot](https://cloud.githubusercontent.com/assets/13502270/21815520/bbd7195a-d711-11e6-905c-1cdf1a2d4ff5.png)
###### Atom screenshot
