### ISSUE TITLE
Current line does not appear highlighted on minimap

### ISSUE THREAD

**Issue by kenstuddy** [andresmichel/one-dark-theme#13]
### Prerequisites

* [Y] Did you perform a cursory search to see if your bug or enhancement is already reported?

### Description

In Ubuntu 16.04 with Xfce4.12 as my DE, I am unable to see the current line highlighted on the minimap even with "highlight_line": true in my Preferences.sublime-settings file. I am unsure if this issue also exists on Windows, but I believe even on Ubuntu with the default theme I can see the current line highlighted on the minimap which leads me to believe this is an issue with this theme. This is a pretty important feature in my opinion, plus Atom's minimap also has this feature.

### Steps to Reproduce

1. Activate this theme.
2. Open any file with multiple lines.
3. Click on a line and look at the minimap.

**Expected behavior:** I expect the current line to be highlighted on the minimap.
**Actual behavior:** The current line is not highlighted on the minimap.

### Versions
Ubuntu 16.04 LTS with Xfce4.12 
Sublime 3143
Theme - One Dark v1.3.6

### Media

![](https://i.imgur.com/FRzwtJO.jpghttps://i.imgur.com/FRzwtJO.jpg)

**Comment by andresmichel** [comment]
Hello, I checked Sublime Text 3143 on Ubuntu 16.04 with the default theme and the minimap never show the current line highlighted even with "highlight_line": true
