### ISSUE TITLE
Doesn't support icons

### ISSUE THREAD

**Issue by mittalyashu** [andresmichel/one-dark-theme#14]
I have installed a package to show icons. But now it is not showing.

![image](https://user-images.githubusercontent.com/29014463/32495332-454bd164-c3eb-11e7-99b6-917ab56196f7.png)

**Comment by kenstuddy** [comment]
Which icon package are you using? I am using "A File Icon" and it works just fine for me:

![](https://i.imgur.com/MwdprUg.png)

**Comment by mittalyashu** [comment]
Yes, I am using A File Icon only.

Have you done any kind of special modifications in your settings?

**Comment by kud** [comment]
I had to uninstall A File Icon and install it again after installing this theme. :) It works now.

**Comment by mittalyashu** [comment]
I will give it a shot and get back to you.

**Comment by kud** [comment]
proof:

<img width="226" alt="image" src="https://user-images.githubusercontent.com/655838/32942940-ce609bf0-cb8a-11e7-97c3-db93b209ed26.png">

**Comment by mittalyashu** [comment]
Yup. It works. Thanks

**Comment by diego-lipinski-de-castro** [comment]
A did what @kud said but icons wont show up. update: I need to have sublime default zzz A File icon zzz too

**Comment by mittalyashu** [comment]
But that doesn't make any sense, Sublime and Atom packages are different.
