### ISSUE TITLE
highlight_line issue

### ISSUE THREAD

**Issue by victorwpbastos** [andresmichel/one-dark-theme#2]
With `hightlight_line: true` in sublime settings, some invalid code is rendered in a color that is very difficult to see:

Example with deleted opening parentesis:
![image](https://cloud.githubusercontent.com/assets/1017515/23316572/b91ba580-faa9-11e6-99d3-bfb77dafdd04.png)

Example with incomplete boolean typed:
![image](https://cloud.githubusercontent.com/assets/1017515/23316599/da603df0-faa9-11e6-9046-9e8fb5ba72f7.png)

BTW, congratulations for the awesome theme. I'm using it for a few days and I'm loving it!

Oh, I'm using Windows 10 64 bits, Sublime Text Build 3126

**Comment by andresmichel** [comment]
Thanks for your comment! I'm glad you like it.
The issue is solved on the last release.
More updates coming soon 👍
