### ISSUE TITLE
Editor them not changed in Ubuntu Sublime 3

### ISSUE THREAD

**Issue by nafeezabrar** [andresmichel/one-dark-theme#28]
I have installed the theme in Sublime Text 3.1.1 Build 2176, on Ubuntu 16.04

Almost all of the component (e.g TabBar, StatusBar, Package Menu) has changed based on the One Dark theme except the editor.

![screenshot from 2019-02-01 10-53-59](https://user-images.githubusercontent.com/3197234/52103617-c6506300-2610-11e9-87c6-c62fffaaf8a2.png)

**Comment by andresmichel** [comment]
I think this is missing 🤔 
"color_scheme": "Packages/Theme - One Dark/One Dark.tmTheme"

**Comment by nafeezabrar** [comment]
Thank you. It works, and sorry for making a silly mistake and for opening this issue.
