### ISSUE TITLE
Cmder theme

### ISSUE THREAD

**Issue by victorwpbastos** [andresmichel/one-dark-theme#3]
Any plans to create a Cmder theme? Would be awesome to get both Sublime and Cmder using the same theme.

**Comment by andresmichel** [comment]
I currently don't have it planned, but maybe in the future 👍

**Comment by loilo** [comment]
For the record (and since this came up pretty high on googling for "cmder one dark"):

Since Cmder is just a nicer frontend for ConEmu, you should be able to use ConEmu color schemes. There's also a One Dark theme [available](https://github.com/joonro/ConEmu-Color-Themes) for that.

**Comment by victorwpbastos** [comment]
Yeah, I ended using that. Thanks!

Em 5 de abr de 2017 8:48 PM, "Florian Reuschel" <notifications@github.com>
escreveu:
