### ISSUE TITLE
White input fields

### ISSUE THREAD

**Issue by floq-design** [andresmichel/one-dark-theme#5]
![screen shot 2017-03-24 at 19 33 59 2](https://cloud.githubusercontent.com/assets/134165/24310889/9242e56e-10c9-11e7-9fdd-d2eaf47d0370.png)
Hi
Can't figure out why, but on my Mac the input fields for Command Palette, Find & Replace etc are dark text on white background, not the other way round as per the screenshots...
Any ideas why?
Cheers
James

**Comment by andresmichel** [comment]
Hello, did you install the theme using Package Control? if not, can you check if the theme folder or package is named "Theme - One Dark".

**Comment by floq-design** [comment]
I downloaded the zip and extracted in my User folder.
Managed to solve it.
Cheers for the support and the theme.
