### ISSUE TITLE
Sidebar style

### ISSUE THREAD

**Issue by emilsgulbis** [andresmichel/one-dark-theme#6]
Hello!
Is there any possibility to get dark sidebar for this theme?

![screen shot 2017-06-06 at 09 12 41](https://cloud.githubusercontent.com/assets/3534160/26816040/5a96b164-4a98-11e7-8f09-035f3dd71f32.png)

**Comment by andresmichel** [comment]
Hello, it seems that only the color scheme was activated, try adding "theme": "One Dark.sublime-theme" on `Preferences > Setting - User` save and restart.

**Comment by emilsgulbis** [comment]
![giphy](https://user-images.githubusercontent.com/3534160/27197375-a8b22aec-5216-11e7-98fc-503eab4da022.gif)

**Comment by andresmichel** [comment]
😂  for better experience try the [recommended settings](https://github.com/andresmichel/one-dark-theme#recommended-settings)
